name = "zeropoint-protocol-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"

[env.production]
name = "zeropoint-protocol-website-prod"

[env.staging]
name = "zeropoint-protocol-website-staging"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[site]
bucket = ".next"
