# Synthiant Bot Configuration
# Owner: DevOps
# Issue: #1401
# PR: #1010 (platform)

name: Synthiant Bot Identity

# Bot configuration for autonomous development
bot:
  name: "synthiant-bot"
  display_name: "Synthiant Development Bot"
  description: "AI-powered development assistant with dual-consensus approval"
  
  # Access permissions (least privilege principle)
  permissions:
    repository:
      contents: write      # Create branches and commit changes
      pull_requests: write # Create and update PRs
      issues: write        # Create and update issues
      metadata: read       # Read repository metadata
      
    # No admin access, no secrets access, no destructive actions
    security_events: read  # Read security events for audit
    actions: read          # Read workflow status for coordination
    
  # Security constraints
  security:
    max_branch_length: 50
    max_commit_message_length: 200
    forbidden_patterns:
      - "rm -rf"
      - "DROP DATABASE"
      - "DELETE FROM"
      - "sudo"
      - "chmod 777"
      
  # Audit logging
  audit:
    log_all_actions: true
    log_decision_reasoning: true
    log_consensus_votes: true
    retention_days: 365
    
  # Rate limiting
  rate_limits:
    max_prs_per_hour: 10
    max_commits_per_hour: 50
    max_branches_per_day: 20
    
  # Consensus requirements
  consensus:
    required_votes: 2
    human_required: true
    timeout_minutes: 30
    fallback_action: "manual_review"
    
  # Ethics and safety
  safety:
    harms_checklist_required: true
    decision_transparency: true
    action_validation: true
    rollback_capability: true

# Integration points
integrations:
  github:
    app_id: "${SYNTHIANT_APP_ID}"
    private_key: "${SYNTHIANT_PRIVATE_KEY}"
    webhook_secret: "${SYNTHIANT_WEBHOOK_SECRET}"
    
  consensus_engine:
    endpoint: "/v1/consensus/{pr}"
    auth_token: "${CONSENSUS_AUTH_TOKEN}"
    
  audit_system:
    endpoint: "/v1/audit/log"
    auth_token: "${AUDIT_AUTH_TOKEN}"

# Workflow templates
workflows:
  autonomy_pipeline:
    name: "Synthiant Autonomy Pipeline"
    description: "AI-driven development with dual-consensus approval"
    
    steps:
      - name: "Plan Development"
        action: "plan"
        timeout: 15m
        
      - name: "Execute Changes"
        action: "execute"
        timeout: 30m
        
      - name: "Create Pull Request"
        action: "create_pr"
        timeout: 10m
        
      - name: "Await Consensus"
        action: "wait_consensus"
        timeout: 30m
        
      - name: "Apply Changes"
        action: "apply"
        timeout: 15m
        condition: "consensus.approved"

# Safety mechanisms
safety:
  emergency_stop:
    enabled: true
    trigger_conditions:
      - "security_violation"
      - "consensus_timeout"
      - "manual_override"
      - "rate_limit_exceeded"
      
  rollback:
    enabled: true
    automatic: false
    manual_approval: true
    max_rollback_depth: 5
    
  monitoring:
    real_time: true
    anomaly_detection: true
    performance_tracking: true
    security_scanning: true

# Documentation and compliance
compliance:
  ethics_review: true
  security_review: true
  audit_trail: true
  decision_logging: true
  transparency: true
  
  # Harms checklist integration
  harms_checklist:
    required: true
    template: "templates/harms-checklist.md"
    validation: true
    
  # Threat model integration
  threat_model:
    required: true
    template: "templates/threat-model.md"
    review_frequency: "per_feature"
