name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck || true
      - run: npm test --if-present
      - run: npm run build
      
  generate-evidence:
    runs-on: ubuntu-latest
    needs: build-test
    if: always()
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p evidence/ci
          echo '{"commit":"'"$GITHUB_SHA"'","buildTime":"'"$(date -u +%FT%TZ)"'","phase":"stage2","ciStatus":"'"${{ needs.build-test.result || 'success' }}"'"}' \
          > evidence/ci/ci-build-meta.json
      - uses: actions/upload-artifact@v4
        with:
          name: ci-evidence
          path: evidence/ci/ci-build-meta.json
