name: Debug Workflows

on:
  workflow_dispatch:
    inputs:
      debug_type:
        description: 'What to debug?'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - network
          - files
          - evidence
          - github-api

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug repository files
        if: ${{ github.event.inputs.debug_type == 'all' || github.event.inputs.debug_type == 'files' }}
        run: |
          echo "=== REPOSITORY STRUCTURE ==="
          find . -name "*.yml" -o -name "*.yaml" | head -10
          echo ""
          echo "=== WORKFLOW FILES ==="
          ls -la .github/workflows/
          echo ""
          echo "=== README COMMIT CHECK ==="
          grep -n "commit" README.md || echo "No commit references found"

      - name: Debug evidence files
        if: ${{ github.event.inputs.debug_type == 'all' || github.event.inputs.debug_type == 'evidence' }}
        run: |
          echo "=== EVIDENCE FILES ==="
          ls -la evidence/phase1/verify/1604e587/ 2>/dev/null || echo "Evidence directory not found"
          echo ""
          if [ -f "evidence/phase1/verify/1604e587/index.json" ]; then
            echo "=== EVIDENCE FILE CONTENT ==="
            head -20 evidence/phase1/verify/1604e587/index.json
            echo ""
            echo "=== JSON VALIDATION ==="
            jq . evidence/phase1/verify/1604e587/index.json > /dev/null && echo "✅ Valid JSON" || echo "❌ Invalid JSON"
          fi

      - name: Debug network connectivity
        if: ${{ github.event.inputs.debug_type == 'all' || github.event.inputs.debug_type == 'network' }}
        continue-on-error: true
        run: |
          echo "=== NETWORK CONNECTIVITY ==="
          echo "Testing DNS resolution..."
          nslookup zeropointprotocol.ai || echo "DNS lookup failed"

          echo ""
          echo "Testing HTTP connectivity..."
          curl -I --max-time 10 https://zeropointprotocol.ai/ 2>/dev/null | head -5 || echo "HTTP connection failed"

          echo ""
          echo "Testing API endpoints..."
          for endpoint in "status/version.json" "api/healthz" "api/readyz"; do
            echo "Testing /$endpoint..."
            curl -s --max-time 5 "https://zeropointprotocol.ai/$endpoint" | head -3 || echo "  ❌ Failed"
          done

      - name: Debug GitHub API
        if: ${{ github.event.inputs.debug_type == 'all' || github.event.inputs.debug_type == 'github-api' }}
        run: |
          echo "=== GITHUB API DEBUG ==="
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo ""
          echo "=== RECENT COMMITS ==="
          git log --oneline -3
          echo ""
          echo "=== WORKFLOW FILES ==="
          find .github/workflows -name "*.yml" -exec basename {} \; | head -5

      - name: Test workflow syntax
        run: |
          echo "=== WORKFLOW SYNTAX VALIDATION ==="
          python3 -c "
          import yaml, os
          workflow_dir = '.github/workflows'
          for file in os.listdir(workflow_dir):
              if file.endswith(('.yml', '.yaml')):
                  try:
                      with open(os.path.join(workflow_dir, file)) as f:
                          yaml.safe_load(f)
                      print(f'✅ {file}: Valid')
                  except Exception as e:
                      print(f'❌ {file}: {e}')
          "

      - name: Generate debug report
        run: |
          echo "=== DEBUG REPORT SUMMARY ==="
          echo "Timestamp: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Debug Type: ${{ github.event.inputs.debug_type }}"
          echo ""
          echo "=== KEY FINDINGS ==="
          echo "1. Repository structure check: $(ls -la | wc -l) files/directories"
          echo "2. Workflow files: $(ls .github/workflows/*.yml 2>/dev/null | wc -l) YAML files"
          echo "3. Evidence files: $(ls evidence/phase1/verify/1604e587/ 2>/dev/null | wc -l || echo 0) files"
          echo "4. Network reachable: $(curl -s --max-time 5 https://zeropointprotocol.ai/ > /dev/null && echo 'Yes' || echo 'No')"
          echo ""
          echo "=== RECOMMENDATIONS ==="
          echo "• Check Actions tab for specific error messages"
          echo "• Verify environment variables in deployment"
          echo "• Test API endpoints manually"
          echo "• Review workflow logs for jq/curl failures"
