name = "zeropoint-protocol"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[env.production]
name = "zeropointprotocol-ai"
routes = ["zeropointprotocol.ai/*"]

[env.preview]
name = "zeropointprotocol-ai-preview"
routes = ["zeropointprotocol-ai.pages.dev/*"]
