name = "zeropoint-protocol"
pages_build_output_dir = "public"

# global (dev/preview) bindings
[[kv_namespaces]]
binding = "SYNTHIENT_CONSENSUS"
id = "REPLACE_WITH_PREVIEW_NAMESPACE_ID"

[vars]
# do not set BUILD_COMMIT / BUILD_TIME here. The build script writes them.

# production bindings (Pages requires explicit env block)
[env.production]
route = ""

[[env.production.kv_namespaces]]
binding = "SYNTHIENT_CONSENSUS"
id = "824b2b27ffcf4392b0e34da1cecdf62f"

[env.production.vars]
# status URLs here if they differ per env
PETALS_STATUS_URL = "https://zeropointprotocol.ai/petals/status.json"
WONDERCRAFT_STATUS_URL = "https://zeropointprotocol.ai/wondercraft/status.json"
TINYGRAD_STATUS_URL = "https://zeropointprotocol.ai/tinygrad/status.json"