name = "zeropoint-protocol"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "public"

# Remove site section for Pages projects

[env.production]
name = "zeropoint-protocol"

[env.production.vars]
__BUILD_SHA__ = "6185c88b"
__BUILD_TIME__ = "2025-08-21T18:13:54.061Z"
