name = "zeropoint-protocol"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration - Static deployment
pages_build_output_dir = "public"

# Workers AI binding for Pages Functions
[ai]
binding = "AI"

[env.production]
name = "zeropoint-protocol"

[env.production.ai]
binding = "AI"

[env.production.vars]
BUILD_COMMIT = "9bfe0f25"
BUILD_TIME = "2025-09-11T08:00:00Z"
CI_STATUS = "green"
MOCKS_DISABLED = "1"
TRAINING_ENABLED = "1"
GOVERNANCE_MODE = "dual-consensus"
SYNTHIENTS_ACTIVE = "1"
TINYGRAD_BACKEND = "cpu"
WORKERS_AI_MODEL = "@cf/meta/llama-3.1-8b-instruct"
TEST_TOKEN = "scra-test-token"
ENVIRONMENT = "production"

# Synthient status sources (placeholders; replace with real URLs when ready)
PETALS_STATUS_URL = "https://zeropointprotocol.ai/petals/status.json"
WONDERCRAFT_STATUS_URL = "https://zeropointprotocol.ai/wondercraft/status.json"
TINYGRAD_STATUS_URL = "https://zeropointprotocol.ai/tinygrad/status.json"


