name = "zeropoint-protocol"
pages_build_output_dir = "."

# global (dev/preview) bindings
[[kv_namespaces]]
binding = "SYNTHIENT_CONSENSUS"
id = "REPLACE_WITH_PREVIEW_NAMESPACE_ID"

[vars]
# do not set BUILD_COMMIT / BUILD_TIME here. The build script writes them.
# Global environment variables for all environments
MOCKS_DISABLED = "1"
TRAINING_ENABLED = "1"
GOVERNANCE_MODE = "dual-consensus"
PHASE = "stage2"
CI_STATUS = "green"

# production bindings (Pages requires explicit env block)
[env.production]

[[env.production.kv_namespaces]]
binding = "SYNTHIENT_CONSENSUS"
id = "824b2b27ffcf4392b0e34da1cecdf62f"

[env.production.vars]
# CTO Directive: Environment enforcement
MOCKS_DISABLED = "1"
TRAINING_ENABLED = "1"
SYNTHIENTS_ACTIVE = "1"
GOVERNANCE_MODE = "dual-consensus"
PHASE = "stage2"
CI_STATUS = "green"
COMMIT_SHA = "be63d5a7"
BUILD_TIME = "2025-09-13T00:20:00.000Z"
# Service URLs
TINYGRAD_API_URL = "https://tinygrad.zeropointprotocol.ai"
PETALS_API_URL = "https://petals.zeropointprotocol.ai"
WONDERCRAFT_API_URL = "https://wondercraft.zeropointprotocol.ai"
# Database
DATABASE_URL = "postgresql://user:pass@prod-db:5432/zeropoint"
# Synthients Training and Proposal Systems
SYNTHIENTS_TRAINING = "active"
SYNTHIENTS_PROPOSALS = "enabled"
PETALS_OPERATIONAL = "true"
WONDERCRAFT_OPERATIONAL = "true"
TINYGRAD_OPERATIONAL = "true"
SELF_IMPROVEMENT_ENABLED = "true"