name = "zeropoint-protocol"
compatibility_date = "2024-01-01"

[build]
command = "echo 'Static site - no build required'"
output_dir = "public"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "public"

[env.production]
name = "zeropointprotocol.ai"
routes = ["zeropointprotocol.ai/*"]

[env.preview]
name = "zeropointprotocol-ai.pages.dev"
routes = ["zeropointprotocol-ai.pages.dev/*"]
