[build]
command = "echo 'Static site - no build required'"
output_dir = "public"
node_version = "20"

[build.environment]
MOCKS_DISABLED = "1"
CF_PAGES_COMMIT_SHA = "{{ .Git.ShortSHA }}"
BUILD_TIME = "{{ .Build.Time }}"

[site]
bucket = "public"
entry-point = "public"

[env.production]
name = "zeropointprotocol.ai"
routes = ["zeropointprotocol.ai/*"]

[env.preview]
name = "zeropointprotocol-ai.pages.dev"
routes = ["zeropointprotocol-ai.pages.dev/*"]
