HTTP/2 201 
date: Tue, 26 Aug 2025 22:28:04 GMT
content-type: application/json; charset=utf-8
content-length: 135
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=pDdOexBbpixhQj8DIfppqxvtahoM1b0KJUB1JEzGv3t5cZzaU9o8DSMQHdCibXyMNHheX1UZ20mgI1tcC%2F1%2FgmNM7YL%2Fx0mSm1Z8GWa8TmCygzn%2FOZ41rYyq0WQvUhR8"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9756c296bbfe2222-ORD
alt-svc: h3=":443"; ma=86400

{"proposal_id":"7420eaf6-05d7-40df-b9b6-cfe931f8f4a6","prompt":"hello world","created_at":"2025-08-26T22:28:04.328Z","state":"pending"}