HTTP/2 200 
date: Tue, 26 Aug 2025 22:25:24 GMT
content-type: text/event-stream; charset=utf-8
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=khtGP8QaR9DegXJEtYdqjHW0xZJuzoGL4r15IOHuKhN6Pfxb%2FLpRuLr7Oy6c%2FjCSTMH4R0PltIYe6D9e9J7iC%2BuD9fvHpu%2BReQCgu16DZaZCN08ufXRIrS44pB8HOE72"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9756beb05f54c997-IAD
alt-svc: h3=":443"; ma=86400

: consensus start

event: consensus
data: {"type":"consensus","state":"pending","seq":1,"ts":"2025-08-26T22:25:27.566Z"}

event: consensus
