  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host 25d29376.zeropoint-protocol.pages.dev:443 was resolved.
* IPv6: 2606:4700:310c::ac42:2d04, 2606:4700:310c::ac42:2efc
* IPv4: 172.66.45.4, 172.66.46.252
*   Trying [2606:4700:310c::ac42:2d04]:443...
* Connected to 25d29376.zeropoint-protocol.pages.dev (2606:4700:310c::ac42:2d04) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [342 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [19 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [2578 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=zeropoint-protocol.pages.dev
*  start date: Aug 17 20:03:03 2025 GMT
*  expire date: Nov 15 21:02:37 2025 GMT
*  subjectAltName: host "25d29376.zeropoint-protocol.pages.dev" matched cert's "*.zeropoint-protocol.pages.dev"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://25d29376.zeropoint-protocol.pages.dev/status/version.json
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: 25d29376.zeropoint-protocol.pages.dev]
* [HTTP/2] [1] [:path: /status/version.json]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /status/version.json HTTP/2
> Host: 25d29376.zeropoint-protocol.pages.dev
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 200 
< date: Tue, 02 Sep 2025 22:11:19 GMT
< content-type: application/json; charset=utf-8
< content-length: 105
< access-control-allow-origin: *
< cache-control: no-store
< content-disposition: inline
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
< permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< vary: accept-encoding
< report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=AvAf%2Fv894nJJUusMU4OlN4EslnbrTsPPeJcI%2BHEuUyIEtgwq57i1BiZYlVvAa8dzxvom0ivrOqN3z8VvoSQ99RRwPc6jXh%2FGssoYTYJt63HmPBNKRTeKCJJMtVpmNbrVUlBHaRB%2FR2WjWpBdYPoeLY8%3D"}]}
< nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
< server: cloudflare
< cf-ray: 979057ada96a5986-IAD
< alt-svc: h3=":443"; ma=86400
< 
{ [105 bytes data]
100   105  100   105    0     0    346      0 --:--:-- --:--:-- --:--:--   346
* Connection #0 to host 25d29376.zeropoint-protocol.pages.dev left intact
{"commit":"86b970a9ddb77590ff38464fda3b3e6617be7f31","buildTime":"2025-09-02T22:11:19.340Z","env":"prod"}