  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host a65f5ac9.zeropoint-protocol.pages.dev:443 was resolved.
* IPv6: 2606:4700:310c::ac42:2efc, 2606:4700:310c::ac42:2d04
* IPv4: 172.66.46.252, 172.66.45.4
*   Trying [2606:4700:310c::ac42:2efc]:443...
* Connected to a65f5ac9.zeropoint-protocol.pages.dev (2606:4700:310c::ac42:2efc) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [342 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [19 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [2578 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=zeropoint-protocol.pages.dev
*  start date: Aug 17 20:03:03 2025 GMT
*  expire date: Nov 15 21:02:37 2025 GMT
*  subjectAltName: host "a65f5ac9.zeropoint-protocol.pages.dev" matched cert's "*.zeropoint-protocol.pages.dev"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://a65f5ac9.zeropoint-protocol.pages.dev/status/version.json
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: a65f5ac9.zeropoint-protocol.pages.dev]
* [HTTP/2] [1] [:path: /status/version.json]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /status/version.json HTTP/2
> Host: a65f5ac9.zeropoint-protocol.pages.dev
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 200 
< date: Tue, 02 Sep 2025 22:42:04 GMT
< content-type: application/json; charset=utf-8
< content-length: 141
< access-control-allow-origin: *
< cache-control: no-store
< content-disposition: inline
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
< permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< vary: accept-encoding
< report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=6RVZsRp34xNxslzJcJG8vvXE2a1WGHh5dL8%2Br3V%2BXkwZ3awDFM7yCWwzrJjB4tHG2lnVpbN%2FnFZLT4i16p7Qb4iuR%2Fbmn9CcoQ5yqBwy%2BqNdexNCw9azRbVE7M7vq8fC4cogiCRK7ziNZs9O5uEWEg4%3D"}]}
< nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
< server: cloudflare
< cf-ray: 979084b94fb9c924-IAD
< alt-svc: h3=":443"; ma=86400
< 
{ [141 bytes data]
100   141  100   141    0     0    513      0 --:--:-- --:--:-- --:--:--   514
* Connection #0 to host a65f5ac9.zeropoint-protocol.pages.dev left intact
{"phase":"stage0","commit":"98da6b42c86cda37da33aa7ebcc33f5a7a66d13e","ciStatus":"green","buildTime":"2025-09-02T22:42:04.389Z","env":"prod"}