HTTP/2 200 
date: Fri, 22 Aug 2025 19:16:52 GMT
content-type: application/json; charset=utf-8
content-length: 46
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=WbZ0WrtAQCcBnVU0wNGlgN%2Bk%2FU6%2F9llAlQyZHxT9XuyQBTe1I9ctzygwDnb%2BjT97pxufUWyWdS44t8Imv02T6HuHs2KYHNnO40KrPwYNUlz8PV4LFujF8BE8q%2BVzhwqY"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9734b501aaac8c76-CDG
alt-svc: h3=":443"; ma=86400

{"status":"ok","uptime":0,"commit":"02107f3c"}