HTTP/1.1 200 OK
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url
cache-control: no-store
content-disposition: inline
content-type: application/json; charset=utf-8
x-content-type-options: nosniff
Date: Mon, 01 Sep 2025 18:46:25 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

{"ready":true,"commit":"1e4d82fdcf869c9ed0e57a7eb2ae811c7b717f9d","buildTime":"2025-09-01T18:46:25.171Z","timestamp":"2025-09-01T18:46:25.171Z","services":{"database":"healthy","cache":"healthy","external":"healthy"},"environment":"development"}