HTTP/1.1 200 OK
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url
cache-control: no-store
content-disposition: inline
content-type: application/json; charset=utf-8
x-content-type-options: nosniff
Date: Mon, 01 Sep 2025 18:46:29 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

{"commit":"730e99c5f48c7db769706d652c83fa146b25ce99","buildTime":"2025-09-01T18:46:29.568Z","env":"development","phase":"v20","ciStatus":"development"}