name = "zpp-status"
main = "src/worker.ts"
compatibility_date = "2024-11-06"
routes = [
  { pattern = "zeropointprotocol.ai/status/*", zone_name = "zeropointprotocol.ai" }
]

[vars]
PHASE = "stage2"
CI_STATUS = "green"
COMMIT_SHA = "e3327e41"
BUILD_TIME = "2025-09-12T21:44:56.139Z"
