name = "zpp-status"
main = "src/worker.ts"
compatibility_date = "2024-11-06"
routes = [
  { pattern = "zeropointprotocol.ai/status/*", zone_name = "zeropointprotocol.ai" }
]

[vars]
PHASE = "stage2"
CI_STATUS = "green"
COMMIT_SHA = "443ea3c8"
BUILD_TIME = "2025-09-11T18:25:52.971Z"
