name = "zpp-status"
main = "src/worker.ts"
compatibility_date = "2024-11-06"
routes = [
  { pattern = "zeropointprotocol.ai/status/*", zone_name = "zeropointprotocol.ai" }
]

[vars]
PHASE = "stage2"
CI_STATUS = "green"
COMMIT_SHA = "e7a6770"
BUILD_TIME = "2025-09-11T22:20:00.000Z"
