HTTP/2 200 
date: Sun, 24 Aug 2025 14:57:22 GMT
content-type: application/json; charset=utf-8
content-length: 46
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=mffWuBZGxmX%2Fcv7ltg6ojU6899wcIFg8MRoyIWvrLZXjomfCliS8Iy1Dx753DxyBh5iVJmVresrNsNV4KKTVNGkrZxe6PYbl5QcPAG9qWddCKQ7C"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9743b3a199558bda-IAD
alt-svc: h3=":443"; ma=86400

{"status":"ok","uptime":0,"commit":"33dbbd99"}