HTTP/2 200 
date: Fri, 22 Aug 2025 20:06:45 GMT
content-type: application/json; charset=utf-8
content-length: 37
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=Av%2B4VRHRKufp%2FTMTXafutJcUtBGKLrhBtKYsrXBMf%2B%2FWIZWglf%2BkIH8yLtWWZEJIPxkmAf%2FV7kxVudKhYCkVmIrB7MxgLTt4%2BVv6p0BXw1h8dxvfQAiTwTrv1OwVdKUW"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9734fe141b44709b-CDG
alt-svc: h3=":443"; ma=86400

{"ready":true,"db":true,"cache":true}