# Petals Configuration - Phase X Task 2
# Real Petals client with peer allowlist and bandwidth guardrails

# Peer allowlist - only these peers are allowed to connect
allowed_peers:
  - "peer1.example.com"
  - "peer2.example.com"
  - "trusted_node_001"
  - "trusted_node_002"

# Bandwidth limits per peer (bytes per second)
bandwidth_limits:
  "peer1.example.com": 1048576    # 1 MB/s
  "peer2.example.com": 2097152    # 2 MB/s
  "trusted_node_001": 5242880     # 5 MB/s
  "trusted_node_002": 10485760    # 10 MB/s

# Cache configuration
max_cache_size_gb: 10
cache_cleanup_interval: 3600  # 1 hour

# Health check settings
health_check_interval: 30  # seconds
health_check_timeout: 10   # seconds

# Local fallback settings
local_fallback_enabled: true
local_processing_timeout: 60  # seconds

# Network settings
connection_timeout: 30
max_retries: 3
retry_delay: 5

# Security settings
enable_peer_validation: true
enable_bandwidth_monitoring: true
log_peer_violations: true

# Model-specific settings
models:
  gpt2:
    max_blocks: 12
    block_size: 2048
    preferred_peers: ["trusted_node_001", "trusted_node_002"]
  
  llama2:
    max_blocks: 32
    block_size: 4096
    preferred_peers: ["peer1.example.com", "peer2.example.com"]
