# Synthiant Training Configuration - Phase 5
# Zeropoint Protocol AI Training Pipeline

training:
  # Framework selection
  framework: "auto"  # auto, tinygrad, pytorch
  fallback_framework: "pytorch"
  
  # Model architecture
  model:
    type: "feedforward"
    input_size: 64
    hidden_size: 128
    output_size: 32
    layers: 3
    activation: "relu"
    
  # Training parameters
  training:
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
    optimizer: "adam"
    loss_function: "mse"
    
  # Data configuration
  data:
    train_split: 0.8
    validation_split: 0.1
    test_split: 0.1
    augmentation: true
    normalization: true
    
  # Hardware optimization
  hardware:
    use_gpu: true
    mixed_precision: true
    num_workers: 4
    
  # Monitoring and logging
  monitoring:
    log_interval: 10
    save_interval: 50
    metrics:
      - "loss"
      - "accuracy"
      - "learning_rate"
      - "epoch_time"
      
  # Output configuration
  output:
    save_dir: "artifacts/train"
    model_format: "onnx"  # onnx, torchscript, tinygrad
    save_optimizer: true
    save_config: true
    
  # CI/CD integration
  ci:
    run_on_push: true
    run_on_pr: true
    matrix_testing: true
    artifact_upload: true
    evidence_update: true
    
  # Security and ethics
  security:
    threat_model: true
    harms_checklist: true
    data_privacy: true
    model_explainability: true
    
  # Performance targets
  performance:
    target_accuracy: 0.95
    max_training_time: 3600  # seconds
    memory_limit: "8GB"
    gpu_memory_limit: "4GB"
