HTTP/2 200 
date: Tue, 02 Sep 2025 01:20:31 GMT
content-type: application/json; charset=utf-8
content-length: 225
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=FiecPqAutnSisWWeR%2Btg45Z0qasOQDtBt2ynMWclkme59EBXMo3Tr2G%2FwS6sxBq0fuaJAnXBMT9OPk3wkblO3rQzrpYfXDiKy2FedFfyYLjQLKmb"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 97892f76d8d8b560-IAD
alt-svc: h3=":443"; ma=86400

{"ready":true,"db":true,"cache":true,"commit":"133c62daf5c9dd8eb1ba24eae9369ab157ec2ef7","buildTime":"2025-09-02T01:20:31.846Z","phase":"5","ciStatus":"green","timestamp":"2025-09-02T01:20:31.846Z","environment":"production"}