HTTP/2 200 
date: Tue, 26 Aug 2025 22:19:00 GMT
content-type: application/json; charset=utf-8
content-length: 78
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=6Vsb6xK4F53tKoSOBDtgG1wiQ%2Fv1kCSBkBvq2zIIGgzBbfb%2FvAU5IQr3I%2B16kQtouVX60FSDGFGyWLlp%2BSZTaQShIj2KJWLj1JbYZk4jGnyEi8DR"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9756b54d1f4f28ba-IAD
alt-svc: h3=":443"; ma=86400

{"status":"ok","uptime":0,"commit":"2bb1e1f58a6c50afb7704bba826ba5eab4e6d8a9"}