HTTP/2 200 
date: Tue, 02 Sep 2025 00:38:49 GMT
content-type: application/json; charset=utf-8
content-length: 225
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=eakhjryXtxGpMOu0DRPJ5u4k7e2NRt9jcaGVR2qjz7TPw6cByNxgeG0S9VnwqNGZlxhyOwK%2F6vJjeg7iP6bR%2Fn6attQX9cVSGe2LaCoNuT7RvAS3"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9788f2606d378254-IAD
alt-svc: h3=":443"; ma=86400

{"ready":true,"db":true,"cache":true,"commit":"ef1ec7364741c5449f8bb0059334d99843ecbf90","buildTime":"2025-09-02T00:38:49.739Z","phase":"5","ciStatus":"green","timestamp":"2025-09-02T00:38:49.739Z","environment":"production"}