HTTP/2 200 
date: Tue, 02 Sep 2025 22:13:11 GMT
content-type: application/json; charset=utf-8
content-length: 225
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=Zh%2BzYB1Lxtu3pdw3FGiVBSR2%2BS2VBKFwTssxlMAU7aypDddgbPLMglA0k6o6nBZWodtEWgeJeLmPPkwBfkeYLXeUMqhzo3yPkbnYBWbOLw8znXKl"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 97905a67db0c3903-IAD
alt-svc: h3=":443"; ma=86400

{"ready":true,"db":true,"cache":true,"commit":"e74f5bc973ec25502fd594f1166de331657fe51a","buildTime":"2025-09-02T22:13:11.063Z","phase":"5","ciStatus":"green","timestamp":"2025-09-02T22:13:11.063Z","environment":"production"}