HTTP/2 200 
date: Mon, 25 Aug 2025 15:23:19 GMT
content-type: application/json; charset=utf-8
cf-cache-status: DYNAMIC
server: cloudflare
vary: Accept-Encoding
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=NuheS0zL95IfRYuzCUxBkZXAyCDwbKNbdzdy%2F5WS99xUBG3zJy4OWky9%2F2a7%2FJ8UrbjNIx7A0lYsXtl0SjCZPRQ6UsCYqx0pCvlCknGuJ4lV25RGfrqguDJo0Kj13EiEj5XK8%2FJoPQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
cf-ray: 974c1705af975b7e-VIE

{"status":"ok","uptime":0,"commit":"e6bb8b505199c4f9b440c8b03d9ee975a2e83792"}