HTTP/2 200 
date: Tue, 26 Aug 2025 22:28:04 GMT
content-type: application/json; charset=utf-8
content-length: 101
cache-control: no-store
content-disposition: inline
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=7hnma2BtuxLM3rS1qhbHpyTuzbugUZxJFsF75L0Ehe9Mtioal5PNp6c3A4%2BB5eEnCGMHP2%2FpKGJVyNp37ZAILSt%2F50COsILCIMy8%2FRAyZVNsY1Ct7k%2FqNuDnII6iv%2Bgl"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9756c294dd6af784-IAD
alt-svc: h3=":443"; ma=86400

[{"proposal_id":"p-001","prompt":"sample","created_at":"2025-08-26T22:28:04.017Z","state":"pending"}]