HTTP/2 200 
date: Wed, 03 Sep 2025 04:15:51 GMT
content-type: application/json; charset=utf-8
content-length: 141
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=ETT9SzOvkPFBzJVWgc2pSQmHuCYLVakx4Ue1SbuSY0%2B5%2FmB2%2F6wUd2ez27DZP%2BkGbuAXao%2BH41loUW7bT1alNd4W3Q%2ByhDjWvrAogQWPfGQ4WA0o"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 97926dacbdae2996-IAD
alt-svc: h3=":443"; ma=86400

{"phase":"stage1","commit":"c66be5c02e63d821a5b8ffc9cee19e61f615bb97","ciStatus":"green","buildTime":"2025-09-03T04:15:51.818Z","env":"prod"}