HTTP/2 308 
date: Tue, 26 Aug 2025 17:47:13 GMT
content-length: 0
location: /status/health
access-control-allow-origin: *
cache-control: public, max-age=300
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-content-type-options: nosniff
x-frame-options: DENY
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=yPKSBRrH00mHibBWvf6DGCKNhRqxez53DIJ0SMnsARc3Mc19VJ3wPXAjvMhw4BHHEIsqFXRrSXGR%2BKWBDODIoll52JWsuJoOh47FLZ%2BBWTVlRNC9"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 975527326e810335-MAD
alt-svc: h3=":443"; ma=86400

