HTTP/2 308 
date: Mon, 25 Aug 2025 19:12:03 GMT
content-length: 0
location: /status/health
access-control-allow-origin: *
cache-control: public, max-age=300
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-content-type-options: nosniff
x-frame-options: DENY
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=QgHi4qqVnTVvuKLax4Yr42gMXn9DgDIMpWWdc21ti53kNgxvGMZgR3VE%2FU%2BNvJOtB9VjqV0wBI4BEVh8xk0AXn%2BxMt0CrbQ8yv9%2Bsd0RK5Y%2F7zWU"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 974d6612d8a78ade-AMS
alt-svc: h3=":443"; ma=86400

