HTTP/2 200 
date: Wed, 03 Sep 2025 20:19:25 GMT
content-type: application/json; charset=utf-8
content-length: 141
access-control-allow-origin: *
cache-control: no-store
content-disposition: inline
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-security-policy: default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests
permissions-policy: accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
vary: accept-encoding
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=46In8cofDX0DdkGPNGxmVVF35LHhRnfESnZ1lgSVezTCNBuT5%2FL3K6sBhr5K%2BxrgycN5QzwJn8V1x9Ss%2BHNlB1T7TiHQ95zRgBI2VBqzYgHn2Byj"}]}
nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
server: cloudflare
cf-cache-status: DYNAMIC
cf-ray: 9797f12108c0a4d4-MIA
alt-svc: h3=":443"; ma=86400

{"phase":"stage1","commit":"f3153de5a2610875df6ff72b3b73225de324e300","ciStatus":"green","buildTime":"2025-09-03T20:19:25.021Z","env":"prod"}