[build]
command = "npm ci && VITE_COMMIT=$CF_PAGES_COMMIT_SHA VITE_BUILD_TIME=$(date -u +%FT%TZ) npm run build"
output_dir = ".vercel/output/static"
node_version = "20"

[build.environment]
VITE_COMMIT = "$CF_PAGES_COMMIT_SHA"
VITE_BUILD_TIME = "$(date -u +%FT%TZ)"
