name: ci-local

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Type check
        run: npm run typecheck
        
      - name: Lint
        run: npm run lint
        continue-on-error: true
        
      - name: Build
        run: npm run build
        env:
          DATABASE_URL: "file:./test.db"
          
      - name: Assert status/version.json fields
        run: |
          test -f public/status/version.json
          jq -e '.commit and .buildTime and .phase and (.ciStatus=="green" or .ciStatus=="local")' public/status/version.json >/dev/null
          echo "✅ version.json fields validated"

