name: Deploy, Purge Cache, and Verify
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare Pages
        run: |
          npm ci
          npm run build
          npx wrangler pages deploy . --project-name zeropoint-protocol --commit-dirty=true

  purge:
    runs-on: ubuntu-latest
    needs: deploy
    if: env.CF_API_TOKEN != ''
    steps:
      - name: Purge Status Endpoints Cache
        run: |
          URLS='["https://zeropointprotocol.ai/status/version.json","https://zeropointprotocol.ai/status/synthients.json"]'
          curl -sX POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
           -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" -H "Content-Type: application/json" \
           --data "{\"files\":$URLS}"

  verify:
    runs-on: ubuntu-latest
    needs: [deploy, purge]
    steps:
      - name: Wait for deployment
        run: sleep 30
      
      - name: Probe Fresh Endpoints
        run: |
          probe() { 
            u="$1?cb=$(date +%s)"; 
            out="$(curl -sS -D - "$u" -o body.txt)"; 
            code=$(printf "%s" "$out" | head -1 | awk '{print $2}');
            ctype=$(printf "%s" "$out" | awk 'tolower($0) ~ /^content-type:/{print tolower($0)}' | awk '{print $2}');
            cache=$(printf "%s" "$out" | awk 'tolower($0) ~ /^cf-cache-status:/{print $2}');
            test "$code" = "200" || { head -120 body.txt; exit 1; }
            echo "$u ok ($ctype, CF=$cache)"; 
          }
          
          echo "=== Status Endpoints ==="
          probe https://zeropointprotocol.ai/status/version.json
          probe https://zeropointprotocol.ai/status/synthients.json
          
          echo "=== API Endpoints ==="
          probe https://zeropointprotocol.ai/api/healthz
          probe https://zeropointprotocol.ai/api/readyz
