name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      
      - name: Write version.json from CI
        run: |
          mkdir -p public/status
          echo '{"commit":"'"$GITHUB_SHA"'","buildTime":"'"$(date -u +%FT%TZ)"'","phase":"stage2","ciStatus":"green","env":"prod"}' > public/status/version.json
          
      - run: npm run build
      
      - name: Cloudflare Pages Deploy
        run: npx wrangler pages deploy . --project-name=zeropoint-protocol --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          
  post-deploy-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: |
          curl -f https://zeropointprotocol.ai/api/healthz
          curl -f https://zeropointprotocol.ai/api/readyz
          curl -f https://zeropointprotocol.ai/status/version.json

