name: Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'src/**', 'docusaurus.config.js', 'sidebars.js' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'src/**', 'docusaurus.config.js', 'sidebars.js' ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate Docusaurus config
        run: npx docusaurus swizzle --help
        
      - name: Build documentation
        run: npm run build:static
        
      - name: Check build output
        run: |
          if [ -d "build" ]; then
            echo "Documentation built successfully"
            ls -la build/
          else
            echo "Build failed - no build directory found"
            exit 1
          fi
          
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-build
          path: build/
          retention-days: 30
          
  validate-links:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build documentation
        run: npm run build
        
      - name: Check for broken links
        run: npx docusaurus broken-links
