name: Lighthouse Audit (PR)
on:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start preview server (static public)
        run: |
          python3 -m http.server 3000 -d public &
          npx -y wait-on http://localhost:3000/index.html
      
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000/
          uploadArtifacts: true
          temporaryPublicStorage: true
