name: Lighthouse Audit (Hard Gate)
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Start local preview
        run: |
          nohup npm run preview -- --port 4173 >/tmp/preview.log 2>&1 &
          echo $! > /tmp/preview.pid
          # give the server a moment
          sleep 4

      - name: Install Lighthouse
        run: npm i -g lighthouse@12

      - name: Run Lighthouse against local preview
        run: |
          set -e
          URL="http://localhost:4173/consensus/proposals"
          lighthouse "$URL" --output=json --output-path=lighthouse.json --quiet --chrome-flags="--headless=new"
          cat lighthouse.json | jq '.categories | {performance: .performance.score, accessibility: .accessibility.score, best_practices: ."best-practices".score, seo: .seo.score}'

          # Assert all categories >= 0.80
          jq -e '.categories.performance.score   >= 0.80 and
                  .categories.accessibility.score >= 0.80 and
                  .categories["best-practices"].score >= 0.80 and
                  .categories.seo.score          >= 0.80' lighthouse.json >/dev/null \
            || (echo "Lighthouse gate failed (<80 in one or more categories)"; exit 1)

      - name: Stop preview
        if: always()
        run: |
          if [ -f /tmp/preview.pid ]; then kill $(cat /tmp/preview.pid) || true; fi

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-audit
          path: lighthouse.json
