name: Lighthouse Audit (PR)
on:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: iaai/package-lock.json
      
      - name: Install dependencies
        run: |
          cd iaai
          npm ci
      
      - name: Build project
        run: |
          cd iaai
          npm run build
      
      - name: Start preview server
        run: |
          cd iaai
          nohup npm run start:dev >/tmp/preview.log 2>&1 &
          echo $! > /tmp/preview.pid
          sleep 10
      
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000/
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
      
      - name: Stop preview server
        if: always()
        run: |
          if [ -f /tmp/preview.pid ]; then 
            kill $(cat /tmp/preview.pid) || true
          fi
      
      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-artifacts
          path: .lighthouseci/
