name: link-check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - name: Check README links and site links
        run: node scripts/check-links.mjs | tee artifacts/link-check.log
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: link-check-log
          path: artifacts/link-check.log


