name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Basic test
        run: |
          echo "=== MINIMAL WORKFLOW TEST ==="
          echo "Current time: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "✅ Workflow executed successfully"
          echo "This confirms GitHub Actions are working"
