name: Cloudflare Pages Preview

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: package-lock.json
      
      - name: Build evidence and validate
        run: |
          node scripts/build-dynamic-evidence.mjs || exit 1
          node scripts/build-leaderboard.mjs || exit 1
          if grep -R "Loading\\.\\.\\." -n app public | grep -v README; then 
            echo "Placeholder text found"; 
            exit 1; 
          fi
      
      - name: Deploy Preview
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zeropoint-protocol
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}


