name: quality
on: [pull_request]
defaults: { run: { working-directory: web } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run type-check
      - run: npm run build
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: 'http://localhost:4173'
          configPath: '../.lighthouserc.json'
          uploadArtifacts: true
        env:
          LHCI_PORT: 4173
      - name: Link check
        uses: lycheeverse/lychee-action@v2
        with: { args: '--base . --verbose --no-progress --exclude-mail' }
      - name: Notify on failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const url = pr ? pr.html_url : `run ${context.runId}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: pr.number, body: `❌ quality failed: ${url}`
            });
