name: Rollback Validation (PR)

on:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identify rollback ref (base of PR)
        id: base
        run: |
          echo "ref=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT

      - name: Checkout rollback ref
        run: |
          git checkout ${{ steps.base.outputs.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Upload basic logs
        if: always()
        run: mkdir -p evidence/rollback && cp -r ./. evidence/rollback || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rollback-artifacts
          path: evidence/rollback
