name: Rollback Validation (PR)

on:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: iaai/package-lock.json
      
      - name: Identify rollback ref (base of PR)
        id: base
        run: |
          BASE=$(git merge-base origin/main HEAD)
          echo "rollback_ref=$BASE" >> $GITHUB_OUTPUT
          echo "Rollback target: $BASE"
      
      - name: Test rollback build
        run: |
          set -e
          ROLLBACK_REF="${{ steps.base.outputs.rollback_ref }}"
          echo "Testing rollback to: $ROLLBACK_REF"
          
          # Reset to rollback point
          git reset --hard $ROLLBACK_REF
          
          # Install dependencies
          cd iaai
          npm ci
          
          # Test build
          npm run build
          
          echo "✅ Rollback build successful"
      
      - name: Rollback validation summary
        run: |
          echo "## Rollback Validation ✅" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Rollback build successful" >> $GITHUB_STEP_SUMMARY
          echo "**Rollback Target:** ${{ steps.base.outputs.rollback_ref }}" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** This PR can be safely rolled back if needed." >> $GITHUB_STEP_SUMMARY
