name: Routing Probe
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run routing probe
        run: node scripts/probe-routing.mjs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: routing-probe
          path: evidence/v20/routing/probe.json
      - name: Commit evidence (main only)
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add evidence/v20/routing/probe.json
          git commit -m "auto(v20): routing probe evidence" || true
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git main
