name: verify-alignment
on: [workflow_dispatch, push]
jobs:
  verify-alignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify alignment and API hygiene
        run: |
          set -euo pipefail
          HEAD="$(git rev-parse --short HEAD)"
          j() { curl -fsS "$1" | jq -r "$2"; }

          V="$(j https://zeropointprotocol.ai/status/version.json .commit)"
          H="$(j https://zeropointprotocol.ai/api/healthz .commit)"
          R="$(j https://zeropointprotocol.ai/api/readyz .commit)"
          S="$(curl -fsS https://zeropointprotocol.ai/status/synthients.json 2>/dev/null | jq -r .commit // empty)"
          test "$V" = "$HEAD" -a "$H" = "$HEAD" -a "$R" = "$HEAD" -a "${S:-$HEAD}" = "$HEAD" || { echo "Commit mismatch"; exit 1; }

          for p in healthz readyz synthient/status synthient/proposals; do
            curl -si https://zeropointprotocol.ai/api/$p | grep -qi 'content-type: application/json' || exit 1
          done
          curl -si https://zeropointprotocol.ai/api/tinygrad/start         | grep -q ' 405 ' || exit 1
          curl -si https://zeropointprotocol.ai/api/petals/propose         | grep -q ' 405 ' || exit 1
          curl -si https://zeropointprotocol.ai/api/wondercraft/contribute | grep -q ' 405 ' || exit 1

          curl -si "https://zeropointprotocol.ai/evidence/phase2/verify/$HEAD/index.json" | grep -qi 'content-type: application/json' || exit 1
