name: verify-alignment
on: [workflow_dispatch, push]
jobs:
  verify-alignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify alignment and API hygiene
        run: |
          set -euo pipefail
          HEAD="$(git rev-parse --short HEAD)"
          j() { curl -fsS "$1" | jq -r "$2"; }

          echo "=== Verifying commit alignment ==="
          echo "Repository HEAD: $HEAD"
          
          V="$(j https://zeropointprotocol.ai/status/version.json .commit)"
          H="$(j https://zeropointprotocol.ai/api/healthz .commit)"
          R="$(j https://zeropointprotocol.ai/api/readyz .commit)"
          T="$(j https://zeropointprotocol.ai/api/training .commit)"
          P="$(j https://zeropointprotocol.ai/api/proposals .commit)"
          S="$(curl -fsS https://zeropointprotocol.ai/status/synthients.json 2>/dev/null | jq -r .commit // empty)"
          
          echo "Status version.json: $V"
          echo "API healthz: $H"
          echo "API readyz: $R"
          echo "API training: $T"
          echo "API proposals: $P"
          echo "Status synthients: ${S:-empty}"
          
          # Check all endpoints match HEAD
          if [ "$V" != "$HEAD" ] || [ "$H" != "$HEAD" ] || [ "$R" != "$HEAD" ] || [ "$T" != "$HEAD" ] || [ "$P" != "$HEAD" ]; then
            echo "❌ Commit mismatch detected!"
            echo "Expected: $HEAD"
            echo "Status version.json: $V"
            echo "API healthz: $H"
            echo "API readyz: $R"
            echo "API training: $T"
            echo "API proposals: $P"
            exit 1
          fi
          
          echo "✅ All endpoints match HEAD commit: $HEAD"

          echo "=== Verifying API responses ==="
          for p in healthz readyz training proposals; do
            echo "Checking /api/$p..."
            if ! curl -si https://zeropointprotocol.ai/api/$p | grep -qi 'content-type: application/json'; then
              echo "❌ /api/$p does not return JSON"
              exit 1
            fi
          done
          
          echo "=== Verifying evidence ==="
          if ! curl -si "https://zeropointprotocol.ai/evidence/phase2/verify/$HEAD/index.json" | grep -qi 'content-type: application/json'; then
            echo "❌ Evidence file missing for commit $HEAD"
            exit 1
          fi
          
          echo "✅ All verification checks passed"
