name: verification-gate
on:
  pull_request: { branches: [ main ] }
  push:        { branches: [ main ] }
  workflow_dispatch: {}
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          npm i -g @lhci/cli@0.14.x
      - name: Probe endpoints
        run: |
          set -euo pipefail
          mkdir -p evidence_out
          probe(){ curl -sS -i "$1" | tee "evidence_out/$2.http" >/dev/null; }
          probe https://zeropointprotocol.ai/api/healthz        api_healthz
          probe https://zeropointprotocol.ai/api/readyz         api_readyz
          probe https://zeropointprotocol.ai/status/version.json status_version_json
          probe https://zeropointprotocol.ai/status/health/      status_health
          probe https://zeropointprotocol.ai/status/ready/       status_ready
          probe https://zeropointprotocol.ai/status/version/     status_version
      - name: Validate headers + JSON (robust)
        run: |
          set -euo pipefail
          # Hard requirements
          grep -qi '^HTTP/.* 200' evidence_out/api_healthz.http
          grep -qi '^HTTP/.* 200' evidence_out/api_readyz.http
          grep -qi '^Content-Type: *application/json' evidence_out/status_version_json.http
          # Extract JSON body after the first blank line (handles CRLF)
          BODY=$(awk 'BEGIN{b=0} { if(b) print; if($0=="" || $0=="\r") {b=1}}' evidence_out/status_version_json.http)
          echo "$BODY" | jq -e 'has("commit") and has("buildTime") and has("env")' >/dev/null
          
          # Soft header checks: pass if present on live OR declared in repo public/_headers
          warn_if_missing(){
            local header="$1"
            if grep -qi "^$header" evidence_out/status_version_json.http; then
              echo "✅ $header present on live"
            elif grep -qi "${header%:*}" public/_headers; then
              echo "⚠️ $header missing on live; policy present in public/_headers (deploy pending)"
            else
              echo "❌ $header missing on live and not declared in public/_headers" && exit 1
            fi
          }
          warn_if_missing 'X-Content-Type-Options: *nosniff'
          warn_if_missing 'Cache-Control: *no-store'
          warn_if_missing 'Strict-Transport-Security:'
          warn_if_missing 'Content-Security-Policy:'
          warn_if_missing 'Referrer-Policy:'
          warn_if_missing 'Permissions-Policy:'
      - name: Lighthouse
        run: |
          mkdir -p lhci
          lhci autorun --collect.url=https://zeropointprotocol.ai/ \
                       --upload.target=filesystem --upload.outputDir=lhci || true

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verification-artifacts
          path: |
            evidence_out/**
            lhci/**
          if-no-files-found: warn

      - name: List artifact names
        if: always()
        run: echo "artifact=verification-artifacts"

      - name: Auto-commit evidence to repo (on main only)
        if: success() && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p public/evidence/v19/curl
          cp evidence_out/*.http public/evidence/v19/curl/
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add public/evidence/v19/curl/
          git commit -m "auto: update v19 curl evidences from CI" || true
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git main
