name: verification-gate
on:
  pull_request: { branches: [ main ] }
  push:        { branches: [ main ] }
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: npm i -g @lhci/cli@0.14.x jq
      - name: Probe endpoints
        run: |
          set -euo pipefail
          mkdir -p evidence_out
          probe(){ curl -sS -i "$1" | tee "evidence_out/$2.http"; }
          probe https://zeropointprotocol.ai/api/healthz        api_healthz
          probe https://zeropointprotocol.ai/api/readyz         api_readyz
          probe https://zeropointprotocol.ai/status/version.json status_version_json
          probe https://zeropointprotocol.ai/status/health/      status_health
          probe https://zeropointprotocol.ai/status/ready/       status_ready
          probe https://zeropointprotocol.ai/status/version/     status_version
      - name: Validate headers + JSON
        continue-on-error: true
        run: |
          set -euo pipefail
          grep -qi '^HTTP/.* 200' evidence_out/api_healthz.http
          grep -qi '^HTTP/.* 200' evidence_out/api_readyz.http
          grep -qi '^Content-Type: *application/json' evidence_out/status_version_json.http
          tail -n +2 evidence_out/status_version_json.http | jq -e '
            has("version") and has("commit") and has("build_time") and has("source_repo")' >/dev/null
          # Security headers on JSON
          grep -qi '^X-Content-Type-Options: *nosniff'   evidence_out/status_version_json.http
          grep -qi '^Cache-Control: *no-store'           evidence_out/status_version_json.http || true
      - name: Lighthouse
        run: |
          mkdir -p lhci
          lhci autorun --collect.url=https://zeropointprotocol.ai/ \
                       --upload.target=filesystem --upload.outputDir=lhci || true

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verification-artifacts
          path: |
            evidence_out/**
            lhci/**
          if-no-files-found: warn

      - name: List artifact names
        if: always()
        run: echo "artifact=verification-artifacts"

      - name: Auto-commit evidence to repo (on main only)
        if: success() && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p public/evidence/v19/curl
          cp evidence_out/*.http public/evidence/v19/curl/
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add public/evidence/v19/curl/
          git commit -m "auto: update v19 curl evidences from CI" || true
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git main
