name: verification-gate
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          npm i -g @lhci/cli@0.14.x jq

      - name: Probe endpoints
        run: |
          set -euo pipefail
          mkdir -p evidence_out
          probe() { url="$1"; fn="$2"; curl -sS -i "$url" | tee "evidence_out/${fn}.http"; }
          probe "https://zeropoint-protocol.pages.dev/api/healthz" "api_healthz"
          probe "https://zeropoint-protocol.pages.dev/api/readyz" "api_readyz"
          probe "https://zeropoint-protocol.pages.dev/status/version.json" "status_version_json"
          probe "https://zeropoint-protocol.pages.dev/status/health/" "status_health"
          probe "https://zeropoint-protocol.pages.dev/status/ready/" "status_ready"
          probe "https://zeropoint-protocol.pages.dev/status/version/" "status_version"

      - name: Validate headers and JSON
        run: |
          set -euo pipefail
          req_hdr() { f="$1"; grep -qiE '^Content-Type:.*(application/json|text/html)' "$f"; }
          json_ok() { f="$1"; tail -n +2 "$f" | jq -e . >/dev/null 2>&1; }
          req_hdr evidence_out/api_healthz.http
          req_hdr evidence_out/api_readyz.http
          req_hdr evidence_out/status_version_json.http
          json_ok evidence_out/status_version_json.http

      - name: Lighthouse (prod)
        run: |
          mkdir -p lhci
          lhci autorun --collect.url=https://zeropoint-protocol.pages.dev/ --upload.target=filesystem --upload.outputDir=lhci

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verification-artifacts
          path: |
            evidence_out/**
            lhci/**

      - name: Write compliance stub
        run: |
          mkdir -p evidence/compliance/$(date -u +%F)
          {
            echo "# Verification Gate — $(date -u +%F)"
            echo ""
            echo "Artifacts: GitHub Actions » verification-artifacts"
            echo ""
            echo "Endpoints probed and Lighthouse run. See artifacts for headers and JSON bodies."
          } > evidence/compliance/$(date -u +%F)/report.md

      - name: Upload compliance stub
        uses: actions/upload-artifact@v4
        with:
          name: compliance-report
          path: evidence/compliance/**

  block-merge:
    if: github.event_name == 'pull_request'
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ensure branch protection requires job 'verify' to pass."
