name: Workflow Failure Alerts

on:
  workflow_run:
    workflows: ["Phase 5 - Sonic MAX Verify", "daily-probe", "Simple Validation (Static Files + API)", "Post-Merge Production Verification", "Push Validation (Direct to Main)"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  alert-on-failure:
    permissions:
      issues: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out' || github.event.workflow_run.conclusion == 'cancelled' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create issue for failed run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          RUN_ID="${{ github.event.workflow_run.id }}"
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${RUN_ID}"
          TITLE="[ALERT] Workflow failed: ${{ github.event.workflow_run.name }} (#${RUN_ID})"
          BODY=$(cat <<EOF
          A workflow run failed.

          - Name: ${{ github.event.workflow_run.name }}
          - Status: ${{ github.event.workflow_run.status }}
          - Conclusion: ${{ github.event.workflow_run.conclusion }}
          - Event: ${{ github.event.workflow_run.event }}
          - Run URL: ${RUN_URL}
          - Head SHA: ${{ github.event.workflow_run.head_sha }}
          - Branch: ${{ github.event.workflow_run.head_branch }}

          Please investigate within SLA.
          EOF
          )
          gh issue create --repo "$REPO" --title "$TITLE" --body "$BODY" --label "analyst-finding,P1"

      - name: Notify Slack (optional)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            RUN_ID="${{ github.event.workflow_run.id }}"
            RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${RUN_ID}"
            payload=$(jq -n --arg text "Workflow failed: ${{ github.event.workflow_run.name }}. See ${RUN_URL}" '{text: $text}')
            curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
          else
            echo "SLACK_WEBHOOK_URL not set, skipping Slack notification"
          fi
