name: Workflow Failure Alerts

on:
  workflow_run:
    # Alert only on critical workflows to reduce noise
    workflows: [
      "verification-gate",
      "auto-deploy",
      "phase5-verify",
      "post-merge-verify",
      "push-validation",
      "routing-probe",
      "lighthouse-audit"
    ]
    types: [completed]
  workflow_dispatch: {}

jobs:
  alert-on-failure:
    permissions:
      issues: write
      contents: read
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out' || github.event.workflow_run.conclusion == 'cancelled' }}
    runs-on: ubuntu-latest
    concurrency:
      group: failure-alert-${{ github.event.workflow_run.id }}
      cancel-in-progress: false
    steps:
      - name: Create issue for failed run
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const title = `[ALERT] Workflow failed: ${run.name} (#${run.id})`;
            const body = [
              'A workflow run failed.',
              '',
              `- Name: ${run.name}`,
              `- Status: ${run.status}`,
              `- Conclusion: ${run.conclusion}`,
              `- Event: ${run.event}`,
              `- Run URL: ${run.html_url}`,
              `- Head SHA: ${run.head_sha}`,
              `- Branch: ${run.head_branch}`,
              '',
              'Please investigate.'
            ].join('\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['analyst-finding','P1']
            });

      - name: Notify Slack (optional)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            RUN_ID="${{ github.event.workflow_run.id }}"
            RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${RUN_ID}"
            payload=$(jq -n --arg text "Workflow failed: ${{ github.event.workflow_run.name }}. See ${RUN_URL}" '{text: $text}')
            curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
          else
            echo "SLACK_WEBHOOK_URL not set, skipping Slack notification"
          fi
